[package]
name = "mochi-plugin-chrono"
description = "All-in-one Clock, Stopwatch, and Timer for Mochi"
version = "0.2.0"
edition = "2024"
license = "MIT"
publish = false

[[bin]]
name = "chrono"
path = "src/main.rs"

[dependencies]
mochi-sdk = { git = "https://github.com/DavidutzDev/mochi" }
serde = { version = "1", features = ["derive"] }
tokio = { version = "1", features = ["macros", "process", "time"] }
libc = "0.2"
